name: Wiki Sync

on:
  gollum:
  push:
    branches: [ wiki ]
    paths:
      - "docs/**"
  repository_dispatch:
    types: [docs]
  
env:
  GIT_BOT_NAME: "github-actions[bot]"
  GIT_BOT_EMAIL: "github-actions[bot]@users.noreply.github.com"
  
jobs:
  job-sync-docs-to-wiki:
    runs-on: ubuntu-latest
    if: github.event_name != 'gollum'
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v2
      
      - name: Sync docs/ to wiki
        uses: newrelic/wiki-sync-action@v1.0.0
        with:
          source: "docs"
          destination: "wiki"
          token: ${{ secrets.WIKI_SYNC_TOKEN }}
          gitAuthorName: ${{ env.GIT_BOT_NAME }}
          gitAuthorEmail: ${{ env.GIT_BOT_EMAIL }}
          branch: wiki
          commitMessage: "Wiki Sync from docs/"
          
  job-sync-wiki-to-docs:
    runs-on: ubuntu-latest
    if: github.event_name == 'gollum'
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v2
        with:
          token: ${{ secrets.WIKI_SYNC_TOKEN }}
          ref: wiki
          
      - name: Sync to wiki docs/
        uses: newrelic/wiki-sync-action@v1.0.0
        with:
          source: "wiki"
          destination: "docs"
          token: ${{ secrets.WIKI_SYNC_TOKEN }}
          gitAuthorName: ${{ env.GIT_BOT_NAME }}
          gitAuthorEmail: ${{ env.GIT_BOT_EMAIL }}
          branch: wiki
          commitMessage: "docs/ Sync from Wiki"
